### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by lingxuanhao** [Turoad/CLRNet#24]
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
even if reduced batch size to 1, still shows up this error

**Comment by lingxuanhao** [comment]
tried with following, it worked, but did not know why. lol
pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by Debugerss** [comment]
点赞

**Comment by TfeiSong** [comment]
点赞

**Comment by 315386775** [comment]
good job

**Comment by gwj-gwj** [comment]
thanks!

**Comment by Garfield-Finch** [comment]
Thank you! It works for me.

**Comment by sjg918** [comment]
THX !!!!!!!!!!!!

**Comment by Albertchamberlain** [comment]
> tried with following, it worked, but did not know why. lol尝试了以下内容，它起作用了，但不知道为什么。哈哈 pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.htmlpip安装torch==1.8.0+cu111 torchvision==0.9.0+cu111 torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

Thx ☆⌒(*＾-゜)v THX!!
